use_frameworks!

platform :ios, '8.0'

target 'HZSAlertViewManager_Example' do
  pod 'HZSAlertViewManager', :path => '../'

  target 'HZSAlertViewManager_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
